site_name: Pitaya Blog
site_url: https://pitayapj.github.io
theme:
  name: material
  favicon: common/img/logo.png
  logo: common/img/logo.png
nav:
  - Home: index.md
  - Devops: index.md
  - Serverless:
    - Building an application in IAM Identity Center(SSO): serverless/application-in-iamic.md