site_name: Pitaya Blog
site_url: https://pitayapj.github.io
theme:
  name: material
  favicon: common/img/logo.png
  logo: common/img/logo.png
  palette: 
    primary: white
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pitayapj
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Devops: devops/index.md
  - Serverless:
    - Building an application in IAM Identity Center(SSO): serverless/app-in-iamic/application-in-iamic.md